const data = [
  { name: "Global Shariah" },
  { name: "Short and Leveraged" },
  { name: "Super Liquid" },
  { name: "CNBC" },
  { name: "Ex Russia" },
  { name: "Frontier" },
  { name: "Global China A Inclusion" },
  { name: "Global Equity (inc. All-World, Emerging)" },
  { name: "MPF Hong Kong" },
  { name: "Multinationals" },
  { name: "Renaissance IPO" },
  { name: "Russell Frontier" },
  { name: "Russell Global" },
  { name: "Russell Stability" },
  { name: "Russell-IdealRatings Islamic" },
  { name: "All-World ex Australia Net Tax (Super)" },
  { name: "Domestic and Global Exposure" },
  { name: "EPRA Nareit Global Real Estate" },
  { name: "Fair Value" },
  { name: "Global Style" },
  { name: "Gold Mines" },
  { name: "High Dividend Yield" },
  { name: "Infrastructure" },
  { name: "Sustainable Yield" },
  { name: "Sustainable Yield 150 Capped 10%" },
  { name: "Italia (inc. FTSE MIB)" },
  { name: "JSE" },
  { name: "AIM (UK)" },
  { name: "ASEA Pan Africa" },
  { name: "ATHEX" },
  { name: "CSE Morocco" },
  { name: "CySE" },
  { name: "European" },
  { name: "FTSEurofirst" },
  { name: "Italia (inc. FTSE MIB) - Italian" },
  { name: "LATIBEX" },
  { name: "Med" },
  { name: "Nasdaq Dubai" },
  { name: "Nordic" },
  { name: "NSE Kenya" },
  { name: "NSX" },
  { name: "Saudi Arabia Inclusion" },
  { name: "techMARK" },
  { name: "UK (inc. FTSE 100, FTSE All-Share)" },
  { name: "Tradable Plus" },
  { name: "Volatility Target" },
  { name: "Canada All Cap Sectors Capped" },
  { name: "Russell US" },
  { name: "Russell US Style" },
  { name: "US Total Market (USTMI)" },
  { name: "Index-level Composite" },
  { name: "Nareit US Real Estate" },
  { name: "ASFA Australia" },
  { name: "Bursa Malaysia" },
  { name: "Russell/Nomura" },
  { name: "SET" },
  { name: "SGX Shariah" },
  { name: "Straits Times and FTSE ST" },
  { name: "TWSE Taiwan" },
  { name: "Vietnam" },
  { name: "ASEAN" },
  { name: "China (inc. China A50, China 50)" },
  { name: "RAFI" },
  { name: "Minimum Variance" },
  { name: "Diversification Based Investing (DBI)" },
  { name: "EDHEC-Risk Efficient" },
  { name: "Equal Risk Contribution (ERC)" },
  { name: "GDP Weighted" },
  { name: "GWA" },
  { name: "High Dividend Low Volatility" },
  { name: "Low Beta Equal Weight" },
  { name: "RAFI Equity Income" },
  { name: "RAFI Low Volatility" },
  { name: "Russell Geographic Exposure" },
  { name: "Russell RAFI" },
  { name: "Russell RAFI Select Real Estate" },
  { name: "Equally Weighted" },
  { name: "FTSE Dividend Growth" },
  { name: "Russell Equal Weight" },
  { name: "Russell Pure Style" },
  { name: "Russell US High Efficiency™ Defensive" },
  { name: "US Risk Premium" },
  { name: "Global Factor (Momentum, Quality, Size, Value..." },
  { name: "Smart Sustainability" },
  { name: "Divest-Invest" },
  { name: "Environmental Markets" },
  { name: "ESG" },
  { name: "ex Fossil Fuels" },
  { name: "FTSE4Good" },
  { name: "Global Choice" },
  { name: "Global Climate" },
  { name: "Green Revenues" },
  { name: "Women on Boards Leadership" },
  { name: "Blossom Japan" },
  { name: "Blossom Japan - Japanese" },
  { name: "Russell Australia ESG High Dividend" },
  { name: "Global Bonds" },
  { name: "FTSE WGBI*" },
  { name: "FTSE WorldBIG*" },
  { name: "Actuaries UK Gilts" },
  { name: "ORB" },
  { name: "FTSE MTS" },
  { name: "NSE KES Government Bond" },
  { name: "FTSE TMX" },
  { name: "Canada Fixed Income" },
  { name: "BOCHK Offshore RMB Bond" },
  { name: "ASFA Australia Bond" },
  { name: "China Onshore Bond" },
  { name: "SBI Bond Index Series" },
  { name: "£SONET" },
  { name: "3 Month US T-Bill + 4%" },
  { name: "World Parity Unit (WPU)" },
  { name: "Cürex FX" },
  { name: "Forward Rate Bias (FRB)" },
  { name: "Russell Conscious Currency" },
  { name: "Target Exposure Commodity" },
  { name: "FTSE 100 Total Return Declared Dividend Expir..." },
  { name: "Implied Volatility" },
  { name: "Private Investor" },
  { name: "UK DC Benchmark" },
  { name: "UK Level Annuity" },
  { name: "Custom Index Methodologies" },
  { name: "Beyond BRICs" },
  { name: "BRIC 50" },
  { name: "MFGAM Core Infrastructure" },
  { name: "MV Exchanges" },
  { name: "Coast Kuwait 40" },
  { name: "Nigeria IPF" },
  { name: "Russia IOB" },
  { name: "UK Digital Services" },
  { name: "All-World Consar Compliant" },
  { name: "Andean 40" },
  { name: "BIVA" },
  { name: "Mexico REITS 25% Capped" },
  { name: "Value-Stocks" }
];

export default data;
